<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUqODLOw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUqODLOw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUqODLOw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUqODLOw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUqODLOw\App_KernelDevDebugContainer([
    'container.build_hash' => 'UqODLOw',
    'container.build_id' => '309d85ea',
    'container.build_time' => 1719414288,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUqODLOw');
