<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5ih0tH5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5ih0tH5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5ih0tH5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5ih0tH5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5ih0tH5\App_KernelDevDebugContainer([
    'container.build_hash' => '5ih0tH5',
    'container.build_id' => 'fa46be03',
    'container.build_time' => 1719223348,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container5ih0tH5');
