<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNEZ0sjF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNEZ0sjF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNEZ0sjF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNEZ0sjF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNEZ0sjF\App_KernelDevDebugContainer([
    'container.build_hash' => 'NEZ0sjF',
    'container.build_id' => 'f4364140',
    'container.build_time' => 1719241431,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNEZ0sjF');
